### ISSUE TITLE
Commit as often as we save?

### ISSUE THREAD

**Issue by pabrams** [esdc-devcop/strategy#25]
What is the reasoning behind the [commit as often as you save](https://github.com/esdc-devcop/strategy/blob/master/guides/working-with-git.md) guideline? I know we're also saying to always squash, but I'd personally still always have a meaningful commit message describing the change, and I'd want to run my tests and make sure the application still builds as well, before committing.

**Comment by s-laugh** [comment]
The idea behind committing as often as you save is under the pretense that you have made a change to the code with an idea in mind, and you want to see if the change works (compiling and passing tests). Even if it doesn't completely work, it was an attempt with a rational behind it, and that makes for a meaningful commit message. 

The benefit is actually shown when you start trying different things to fix an issue; if you keep saving and testing in small increments you now have a history of everything you have tried. If you want to pull just a small part of the attempts out because it worked but everything else got a little messy, it's really easy to do that (without actually coding or un-coding anything)! The other benefit, is for other people, when reviewing your code in a case where they have to take over the development, they can see your thought process throughout your development and they will be able to pick it up faster.

**Comment by pabrams** [comment]
Are we talking about save as in CTRL+S?  I do that constantly, and there's no way I would even consider doing `git commit` every time I do CTRL+S.  Are you saying you only save your changes to disk after compiling and testing (or when you're ready to compile and test)?  

Of course I agree that commits should be small, and of course I agree that there should be meaningful comments, but I don't see what that has to do with "commit as often as you save".  I can't follow that guideline.

**Comment by pabrams** [comment]
That would be a huge change for me, but maybe after I got in the habit, it wouldn't add much overhead.  In some ways I kind of like the idea, but aren't we just deleting the branch anyway?  And squash merging as well?  So we're just going to lose all those commit messages?

**Comment by s-laugh** [comment]
It's more in line with the "Commit Often" sentiment that is heard almost everywhere. Commit as often as you save, is a little on the extreme side, but it puts context as to what _often_ means. And coming from a culture where most developers commit (or _check-in_ in TFS terms) only after a whole feature is developed and unit tested; _often_ doesn't have much context. So setting the context and being a little extreme help push for the urgency and need for change in how developers work.

You are right, once squashed the many commits don't have any more value, but that doesn't negate the value they have thought the development process. Once the feature or fix is complete we only need one commit to track that change, not all the attempts or stages of development that were committed. 

As for committing broken code, I would agree, and typically my work flow involves: save, compile, run test(s), commit, launch and manual test. But I have also intentionally committed broken code just to save a point of reference (it also helps remind me that I didn't finish what I was working on).

**Comment by pabrams** [comment]
I normally use `git stash` for unfinished work that I want to save on the server, but I don't think it's a big deal if you want to commit it as long as it gets squashed out later.
